# Generated by Django 5.0 on 2023-12-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Season_End_Year', models.IntegerField()),
                ('Team', models.CharField(max_length=100)),
                ('Rk', models.IntegerField()),
                ('MP', models.IntegerField()),
                ('W', models.IntegerField()),
                ('D', models.IntegerField()),
                ('L', models.IntegerField()),
                ('GF', models.IntegerField()),
                ('GA', models.IntegerField()),
                ('GD', models.IntegerField()),
                ('Pts', models.IntegerField()),
                ('Notes', models.CharField(max_length=500)),
            ],
        ),
    ]
